In [1]:
!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in ./venv/lib/python3.9/site-packages (1.2.7)
WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/new/Desktop/Data_Scraping_and-_EDA_Qiyas/venv/bin/python3 -m pip install --upgrade pip' command.

In [2]:
import sys

!{sys.executable} -m pip install google-play-scraper

Requirement already satisfied: google-play-scraper in ./venv/lib/python3.9/site-packages (1.2.7)
WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/new/Desktop/Data_Scraping_and-_EDA_Qiyas/venv/bin/python3 -m pip install --upgrade pip' command.

In [3]:
from google_play_scraper import reviews
from google_play_scraper import Sort
import pandas as pd

In [4]:
apps = {

    "CBE": "com.combanketh.mobilebanking",

    "CBEBirr": "prod.cbe.birr",

    "Dashen": "com.dashen.dashensuperapp",

    "BOA": "com.boa.boaMobileBanking",

    "Apollo (BOA)": "com.boa.apollo",

    "Awash Bank Mobile Banking": "pegasus.project.awash.mobile.android.bundle.mobilebank",

    "Awash Birr Pro": "com.sc.awashpay",

    "Nib Bank Mobile Banking": "com.nib.NibMobileBanking",

    "EBirr": "com.safarifone.ebirr",

    "Telebirr": "cn.tydic.ethiopay" ,
    
    "Dashen Bank Mobile Banking": "com.dashen.dashensuperapp",

    "Oromia Bank Mobile Banking": "com.oromiabank.mobilebanking",

    "Coop Bank Mobile Banking": "8821741740847225624&hl=en",


}

In [5]:
all_reviews = []

In [6]:
from google_play_scraper import reviews, Sort

all_reviews = []

for bank, app_id in apps.items():

    print(f"Scraping reviews for {bank}...")

    try:
        result, continuation_token = reviews(
            app_id,
            country='et',
            sort=Sort.NEWEST,
            count=20000
        )

        print(f"Collected {len(result)} reviews")

        for review in result:

            all_reviews.append({
                "review_id": review["reviewId"],
                "review": review["content"],
                "rating": review["score"],
                "date": review["at"],
                "bank": bank,
                "source": "Google Play"
            })

    except Exception as e:
        print(f"Error scraping {bank}: {e}")

print("Scraping completed.")

Scraping reviews for CBE...
Collected 9822 reviews
Scraping reviews for CBEBirr...
Collected 2302 reviews
Scraping reviews for Dashen...
Collected 1049 reviews
Scraping reviews for BOA...
Collected 1450 reviews
Scraping reviews for Apollo (BOA)...
Collected 2084 reviews
Scraping reviews for Awash Bank Mobile Banking...
Collected 129 reviews
Scraping reviews for Awash Birr Pro...
Collected 3413 reviews
Scraping reviews for Nib Bank Mobile Banking...
Collected 235 reviews
Scraping reviews for EBirr...
Collected 1641 reviews
Scraping reviews for Telebirr...
Collected 16606 reviews
Scraping reviews for Dashen Bank Mobile Banking...
Collected 1049 reviews
Scraping reviews for Oromia Bank Mobile Banking...
Collected 165 reviews
Scraping reviews for Coop Bank Mobile Banking...
Collected 0 reviews
Scraping completed.

In [7]:
print("Total reviews across all apps:", len(all_reviews))

Total reviews across all apps: 39945

In [8]:
import sys
!{sys.executable} -m pip install app-store-scraper

Requirement already satisfied: app-store-scraper in ./venv/lib/python3.9/site-packages (0.3.5)
Requirement already satisfied: requests==2.23.0 in ./venv/lib/python3.9/site-packages (from app-store-scraper) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (2026.5.20)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (1.25.11)
WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/new/Desktop/Data_Scraping_and-_EDA_Qiyas/venv/bin/python3 -m pip install --upgrade pip' command.

In [9]:
!pip install app-store-scraper
import sys
!{sys.executable} -m pip install app-store-scraper

Requirement already satisfied: app-store-scraper in ./venv/lib/python3.9/site-packages (0.3.5)
Requirement already satisfied: requests==2.23.0 in ./venv/lib/python3.9/site-packages (from app-store-scraper) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (2026.5.20)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (3.0.4)
WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/new/Desktop/Data_Scraping_and-_EDA_Qiyas/venv/bin/python3 -m pip install --upgrade pip' command.
Requirement already satisfied: app-store-scraper in ./venv/lib/python3.9/site-packages (0.3.5)
Requirement already satisfied: requests==2.23.0 in ./venv/lib/python3.9/site-packages (from app-store-scraper) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests==2.23.0->app-store-scraper) (2026.5.20)
WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/new/Desktop/Data_Scraping_and-_EDA_Qiyas/venv/bin/python3 -m pip install --upgrade pip' command.

In [10]:
import sys
print(sys.executable)

/Users/new/Desktop/Data_Scraping_and-_EDA_Qiyas/venv/bin/python3

In [11]:
import pandas as pd

df = pd.DataFrame(all_reviews)

print(df.shape)
df.head()

(39945, 6)

,review_id,review,rating,date,bank,source
0,08e5d37c-4ebc-412c-a2a1-6d95368729f4,nice,5,2026-06-16 11:50:10,CBE,Google Play
1,a5dbe495-3811-4898-ae15-19cc65c8983f,do not disturb,5,2026-06-16 10:55:36,CBE,Google Play
2,d3623752-b3f0-4c4e-bd56-8bde8729d839,we,5,2026-06-15 23:20:15,CBE,Google Play
3,7670a249-ab49-4f9f-9cb1-104fef28d9c8,ጠሩ ስራ ነው,1,2026-06-15 22:59:05,CBE,Google Play
4,fb646a73-71f1-4841-88c2-298c015c9690,wow,5,2026-06-15 22:46:51,CBE,Google Play

In [12]:
df.tail()

,review_id,review,rating,date,bank,source
39940,9143c3bc-e8a0-46be-9c32-72c888428944,wow a very popular and attractive app,5,2023-12-25 21:54:53,Oromia Bank Mobile Banking,Google Play
39941,930267b3-fa32-4c13-996f-59dc6ef1c0ef,I will give you 5 rate Wow one the most beauti...,5,2023-12-25 21:23:11,Oromia Bank Mobile Banking,Google Play
39942,7d0e9f1e-b9b6-4f67-aa32-3626d469511d,App Ajaa'ibaati 👌,5,2023-12-25 21:12:11,Oromia Bank Mobile Banking,Google Play
39943,b0101377-6dff-4d25-b756-3333e6666042,Baayyee gaariidha,5,2023-12-25 18:58:26,Oromia Bank Mobile Banking,Google Play
39944,e4ebdac4-2555-401e-8929-2156cef3d27e,"Realy, it is the best oroodijital.",5,2023-12-25 05:04:56,Oromia Bank Mobile Banking,Google Play

In [13]:
df.iloc[10000:10500]

,review_id,review,rating,date,bank,source
10000,d6e2da78-d86f-4fde-9368-154f557d1161,The newly added feature link acc. is not funct...,4,2026-02-03 04:52:41,CBEBirr,Google Play
10001,c16472ae-ea38-41e2-b028-02699418cc25,block na jalaa ta.e maal furmaani isa?,4,2026-02-02 22:58:23,CBEBirr,Google Play
10002,36f394dd-71ac-45f7-8ff3-35e0ae29f083,best apps,5,2026-02-01 22:46:05,CBEBirr,Google Play
10003,4677dcef-6ca0-495b-8d6d-e37e2abc79fb,cbe,5,2026-01-31 10:24:25,CBEBirr,Google Play
10004,9901c288-9960-4406-8cd0-42ff77dc12b4,cbe birr yleyal 🫶,5,2026-01-30 22:24:42,CBEBirr,Google Play
...,...,...,...,...,...,...
10495,530e9346-4da2-46b9-bca9-695e60231ab8,Well app,4,2025-02-28 04:58:54,CBEBirr,Google Play
10496,4b26081e-3a8e-410c-9fde-49eec37b472f,የአካዉንት ቁጥር ካስገባን በኋላ የምንልክለት ሰዉ ትክክለኛ መሆኑን ለማረ...,4,2025-02-26 17:15:49,CBEBirr,Google Play
10497,638756a7-f001-49c5-9461-6ff3d93b0085,Excellent app,5,2025-02-25 19:44:24,CBEBirr,Google Play
10498,3f2386e0-8d9d-4c1a-9830-53ddd82c53d5,It's good app,4,2025-02-24 16:51:02,CBEBirr,Google Play
10499,7a04e135-a5e1-4f6b-9018-cd2d18188d11,The worst app in the world ...,1,2025-02-24 11:40:49,CBEBirr,Google Play

In [14]:
!pip install openpyxl

Requirement already satisfied: openpyxl in ./venv/lib/python3.9/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in ./venv/lib/python3.9/site-packages (from openpyxl) (2.0.0)
WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/new/Desktop/Data_Scraping_and-_EDA_Qiyas/venv/bin/python3 -m pip install --upgrade pip' command.

In [15]:
df.to_excel(
    "ethiopian_banking_reviews.xlsx",
    index=False
)

print("Excel file saved successfully!")

Excel file saved successfully!

In [16]:
import os

print(os.path.exists("ethiopian_banking_reviews.xlsx"))

True

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39945 entries, 0 to 39944
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review_id  39945 non-null  object
 1   review     39938 non-null  object
 2   rating     39945 non-null  int64
 3   date       39945 non-null  datetime64[ns]
 4   bank       39945 non-null  object
 5   source     39945 non-null  object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 1.8+ MB

In [18]:
df.isnull().sum()

review_id    0
review       7
rating       0
date         0
bank         0
source       0
dtype: int64

In [19]:
duplicates = df.duplicated().sum()

print(duplicates)

0

In [ ]:
df['bank'].value_counts()

In [ ]:
import matplotlib.pyplot as plt
df['bank'].value_counts().plot(
    kind='bar',
    figsize=(10,5)
)

plt.title("Number of Reviews per App")
plt.show()

Rating Analysis

In [ ]:
df['rating'].value_counts().sort_index()

In [ ]:
df['rating'].value_counts().sort_index().plot(
    kind='bar'
)

plt.title("Rating Distribution")
plt.show()

In [ ]:
df.groupby('bank')['rating'].mean().sort_values(
    ascending=False
)

In [ ]:
df.groupby('bank')['rating'].mean()\
.sort_values()\
.plot(kind='barh')

In [ ]:
df['review_length'] = df['review'].str.len()

In [ ]:
df['review_length'].describe()

In [ ]:
df['review_length'].hist(
    bins=50
)

Time-Based Analysis

In [ ]:
df['date'] = pd.to_datetime(df['date'])

In [ ]:
monthly_reviews = df.resample(
    'M',
    on='date'
).size()

In [ ]:
monthly_reviews.plot(figsize=(12,5))